# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ff65309032794a0c51f421c9f9ec42749347bdb913d74e8e92cf186390a6faeaf9d42ee7d7dbd877dbbff45929fd4a131a0c06c3b01e615b80ce582e197d6802

test:
  secret_key_base: 6d4b041f4e547cd0bfd4b49883924c6c986120d9d3a628bb86faf5c03604a176c6255c909e4823787c906c9af4660117ac94209a359268708455afe2296c2990

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
